version: '3.9'

services:
  db:
    image: postgres:17
    container_name: planningback-db
    environment:
      POSTGRES_DB: planningback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./planningback.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: planningback-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_NAME: planningback
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata: