# Generated by Django 5.1.5 on 2025-02-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_travail_vacances_employes_contrats_magasin_planning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='name',
            new_name='username',
        ),
    ]
