# Generated by Django 5.1.7 on 2025-04-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_magasin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magasin',
            old_name='user',
            new_name='created_by',
        ),
    ]
