# Generated by Django 5.1.7 on 2025-05-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_vacation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
