# Generated by Django 5.1.5 on 2025-02-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_remove_contrats_employes_remove_magasin_employes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('administrateurs', models.ManyToManyField(to='back.administrateur')),
            ],
        ),
        migrations.AddField(
            model_name='contrats',
            name='employes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.employes'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='employes',
            field=models.ManyToManyField(to='back.employes'),
        ),
        migrations.AddField(
            model_name='planning',
            name='employes',
            field=models.ManyToManyField(to='back.employes'),
        ),
    ]
