# Generated by Django 5.1.7 on 2025-04-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_rename_user_magasin_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('employe', 'Employe')], max_length=15),
        ),
    ]
