# Generated by Django 5.1.7 on 2025-05-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_vacation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='status',
        ),
    ]
