# Generated by Django 5.1.7 on 2025-04-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='assign_to',
        ),
    ]
