# Generated by Django 5.1.7 on 2025-05-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_vacation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_day', to=settings.AUTH_USER_MODEL),
        ),
    ]
