# Generated by Django 5.1.5 on 2025-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_administrateur_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
