# Generated by Django 5.1.7 on 2025-05-09 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_alter_workingday_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='working_day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), null=True, size=7),
        ),
    ]
