# Generated by Django 5.1.7 on 2025-04-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_remove_contrat_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='back.contrat'),
        ),
    ]
