# Generated by Django 5.1.7 on 2025-07-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_alter_vacation_status_planning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planning',
            new_name='PlanningEntry',
        ),
    ]
