# Generated by Django 5.1.7 on 2025-07-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_rename_planning_planningentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningentry',
            name='end_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planningentry',
            name='start_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
